spring:
  profiles:
    active: dev


---
spring:
  profiles:
    active: test
  application:
    name: springcloud-config-user
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
spring:
  profiles:
    active: dev
  application:
    name: springcloud-config-user
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/